INSERT INTO roles (name) VALUES ('ROLE_STUDENT') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_INSTRUCTOR') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;
UPDATE courses SET status = 'PUBLISHED';